### ISSUE TITLE
Release checklist

### ISSUE THREAD

**Issue by AndrewDryga** [Nebo15/man.api#12]
Docs:
- [x] Repository has meaningful README.md that describes what service does.
- [x] Service API matches Apiary description.
- [x] If applicable - there are link to Docker Hub.
- [x] (if repo is public) Docker Hub page links to `/docs/ENVIRONMENT.md` file and repo.
- [x] `README.md` contains list of third-party dependencies: eg. PostgreSQL or some NIF lib.

Configuration:
- [x] All reasonable configuration data is taken from environment variables.
- [x] `.env` file is up to date.
- [x] `/docs/ENVIRONMENT.md` file is present and describes configuration options, what do they mean. Examples: [ael.api](https://github.com/Nebo15/ael.api/blob/master/docs/ENVIRONMENT.md), [annon.infra](https://github.com/Nebo15/annon.infra). README.md links to it. (Or place everything in README.md).
- [x] `LOG_LEVEL` env [is used](https://github.com/Nebo15/ael.api/blob/master/lib/ael_api/application.ex#L14).
- [x] `ERLANG_COOKIE` is [accepted at start-time](https://github.com/Nebo15/annon.api/blob/master/rel/templates/vm.args.eex#L5).

Logging:
- [x] Logs are written in JSON format (`logger_json`).
- [x] Logs does not contain critical data even in DEBUG mode: full dumps of objects that contain it, secrets, tokens, etc. If so - drop log or hide secret from it via Logger configuration (and make sure it's applied).

Security:
- [x] There are no secrets to any service in repository source code. (If not - delete them and tell me to rotate them.)
- [x] There are no secrets that is packed to a container in a CI process. (If not - delete them and tell me to rotate them.)

Debugging in production:
- [x] `:release_tools` in included in application dependencies.
